audioList = {
    mainTheme: new AudioManager("assets/audio/background/Faster_Version-2024-02-19_-_Mexican_Cowboys_-_www.FesliyanStudios.com.mp3", 0.2, true),
    gamePlay: new AudioManager("assets/audio/background/Slower_Version-2023-05-15_-_Chicken_Chase_-_www.FesliyanStudios.com.mp3",0.2, true),
    chicken: new AudioManager("assets/audio/background/mixkit-chickens-and-pigeons-1769.wav", 0.1, false),
    onLanding: new AudioManager("assets/audio/jump-on-chicken/mixkit-falling-hit-on-gravel-756.wav", 0.1, false),
    jumpOnChicken: new AudioManager("assets/audio/jump/mixkit-body-punch-quick-hit-2153.wav", 0.1, false),
    jump: null,
    coinCollected: new AudioManager("assets/audio/collect/mixkit-fairy-arcade-sparkle-866.wav", 0.1, false),
    bottleCollected: new AudioManager("assets/audio/throw/mixkit-wine-glass-clink-2936.wav", 0.1, false),
    fightScene: new AudioManager("assets/audio/endboss-intro/2019-05-09_-_Escape_Chase_-_David_Fesliyan.mp3",0.1,false),
    endbossHurt: new AudioManager("assets/audio/endboss/mixkit-cock-cry-1761.wav", 0.5, false),
    ghost: new AudioManager("assets/audio/ghost/mixkit-video-game-health-recharge-2837.wav", 0.5, false),
    throw: null,
    bottleBreaks: new AudioManager("assets/audio/throw/mixkit-glass-break-with-hammer-thud-759.wav", 0.08, false),
    bottleSplash: new AudioManager("assets/audio/throw/mixkit-gore-video-game-blood-splash-263.wav", 0.08, false),
    characterHurt: new AudioManager("assets/audio/hurt/mixkit-arcade-retro-game-over-213.wav", 0.08, false),
    energyRecovery: new AudioManager("assets/audio/collect/mixkit-extra-bonus-in-a-video-game-2045.wav", 0.08, false),
    walking: new AudioManager("assets/audio/walk/mixkit-footsteps-in-woods-loop-533.wav", 0.5, false),
    characterDead: new AudioManager("assets/audio/game-over/mixkit-player-losing-or-failing-2042.wav", 0.2, false),
    gameOver: new AudioManager("assets/audio/game-over/mixkit-retro-arcade-game-over-470.wav", 0.2, false),
    gameWin: new AudioManager("assets/audio/game-win/mixkit-video-game-win-2016.wav", 0.2, false),
    // idle,
    // snoring,
  };