audioList = {
  mainTheme: new AudioManager("assets/audio/mainTheme.mp3", 0.08, true),
  gamePlay: new AudioManager("assets/audio/gamePlay.mp3", 0.08, true),
  chicken: new AudioManager("assets/audio/chicken.wav", 0.2, false),
  onLanding: new AudioManager("assets/audio/onLanding.wav", 0.2, false),
  jumpOnChicken: new AudioManager("assets/audio/jumpOnChicken.wav", 0.5 , false),
  chickenDead: new AudioManager("assets/audio/chickenDead.mp3", 0.2, false),
  jump: new AudioManager("assets/audio/jump.mp3", 0.5, false),
  coinCollected: new AudioManager("assets/audio/coinCollected.wav", 0.2, false),
  bottleCollected: new AudioManager("assets/audio/bottleCollected.wav", 0.2, false),
  fightScene: new AudioManager("assets/audio/fightScene.mp3",0.3,false),
  endbossHurt: new AudioManager("assets/audio/endbossHurt.wav", 0.5, false),
  ghost: new AudioManager("assets/audio/ghost.wav", 0.2, false),
  throw: new AudioManager("assets/audio/throw.mp3", 0.5, false),
  bottleBreaks: new AudioManager("assets/audio/bottleBreaks.wav", 0.1, false),
  bottleSplash: new AudioManager("assets/audio/bottleSplash.wav", 0.08, false),
  characterHurt: new AudioManager("assets/audio/characterHurt.wav", 0.08, false),
  energyRecovery: new AudioManager("assets/audio/energyRecovery.wav", 0.08, false),
  walking: new AudioManager("assets/audio/walk.mp3", 0.3, false),
  characterDead: new AudioManager("assets/audio/characterDead.wav", 0.5, false),
  gameOver: new AudioManager("assets/audio/gameOver.wav", 0.5, false),
  gameWin: new AudioManager("assets/audio/gameWin.wav", 0.5, false),
  idle: new AudioManager("assets/audio/idle.mp3", 0.5, false),
  snoring: new AudioManager("assets/audio/snoring.mp3", 0.1, false),
};